// data.js — Hardcoded baseline from sabexistcount.com scrape (May 17 2026)
// Bot uses this immediately on startup. Scraper updates it every 6h if possible.

const BASELINE_DATA = {
  "strawberry elephant":           { name: "Strawberry Elephant",           count: 2032,       rarity: "OG",           source: "baseline" },
  "headless horseman":             { name: "Headless Horseman",             count: 165,        rarity: "OG",           source: "baseline" },
  "meowl":                         { name: "Meowl",                         count: 3200,       rarity: "OG",           source: "baseline" },
  "pineaplino":                    { name: "Pineaplino",                    count: 81,         rarity: "Brainrot God", source: "baseline" },
  "pretzo robo":                   { name: "Pretzo Robo",                   count: 541,        rarity: "Brainrot God", source: "baseline" },
  "tralalero tralala":             { name: "Tralalero Tralala",             count: 25019185,   rarity: "Brainrot God", source: "baseline" },
  "unclito samito":                { name: "Unclito Samito",                count: 1107514,    rarity: "Brainrot God", source: "baseline" },
  "lazy ducky":                    { name: "Lazy Ducky",                    count: 2374,       rarity: "Brainrot God", source: "baseline" },
  "brutto gialutto":               { name: "Brutto Gialutto",               count: null,       rarity: "Mythic",       source: "baseline" },
  "tob tobi tobi":                 { name: "Tob Tobi Tobi",                 count: null,       rarity: "Mythic",       source: "baseline" },
  "rhino helicopterino":           { name: "Rhino Helicopterino",           count: null,       rarity: "Mythic",       source: "baseline" },
  "centrucci nuclucci":            { name: "Centrucci Nuclucci",            count: null,       rarity: "Mythic",       source: "baseline" },
  "ganganzelli trulala":           { name: "Ganganzelli Trulala",           count: null,       rarity: "Mythic",       source: "baseline" },
  "avocadorilla":                  { name: "Avocadorilla",                  count: null,       rarity: "Mythic",       source: "baseline" },
  "caramello filtrello":           { name: "Caramello Filtrello",           count: null,       rarity: "Legendary",    source: "baseline" },
  "puffaball":                     { name: "Puffaball",                     count: null,       rarity: "Legendary",    source: "baseline" },
  "malame amarele":                { name: "Malame Amarele",                count: null,       rarity: "Epic",         source: "baseline" },
  "trippi troppi":                 { name: "Trippi Troppi",                 count: null,       rarity: "Rare",         source: "baseline" },
  "raccooni jandelini":            { name: "Raccooni Jandelini",            count: null,       rarity: "Common",       source: "baseline" },
  "pipi corni":                    { name: "Pipi Corni",                    count: null,       rarity: "Common",       source: "baseline" },
  "los tortus":                    { name: "Los Tortus",                    count: 16749210,   rarity: "Secret",       source: "baseline" },
  "bisonte giuppitere":            { name: "Bisonte Giuppitere",            count: null,       rarity: "Secret",       source: "baseline" },
  "la vacca saturno saturnita":    { name: "La Vacca Saturno Saturnita",    count: null,       rarity: "Secret",       source: "baseline" },
  "agarrini la palini":            { name: "Agarrini La Palini",            count: null,       rarity: "Secret",       source: "baseline" },
  "karker sahur":                  { name: "Karker Sahur",                  count: null,       rarity: "Secret",       source: "baseline" },
  "1x1x1x1":                       { name: "1x1x1x1",                       count: null,       rarity: "Secret",       source: "baseline" },
  "cuadramat and pakrahmatmamat":  { name: "Cuadramat and Pakrahmatmamat",  count: null,       rarity: "Secret",       source: "baseline" },
  "tung tung tung sahur":          { name: "Tung Tung Tung Sahur",          count: null,       rarity: "Secret",       source: "baseline" },
  "arcadopus":                     { name: "Arcadopus",                     count: null,       rarity: "Secret",       source: "baseline" },
  "guest 666":                     { name: "Guest 666",                     count: null,       rarity: "Secret",       source: "baseline" },
  "los hotspotsitos":              { name: "Los Hotspotsitos",              count: null,       rarity: "Secret",       source: "baseline" },
  "churrito bunnito (egg)":        { name: "Churrito Bunnito (Egg)",        count: null,       rarity: "Secret",       source: "baseline" },
  "globa steppa":                  { name: "Globa Steppa",                  count: null,       rarity: "Secret",       source: "baseline" },
  "tralaledon":                    { name: "Tralaledon",                    count: null,       rarity: "Secret",       source: "baseline" },
  "esok sekolah":                  { name: "Esok Sekolah",                  count: null,       rarity: "Secret",       source: "baseline" },
  "los mariachis":                 { name: "Los Mariachis",                 count: null,       rarity: "Secret",       source: "baseline" },
  "los puggies":                   { name: "Los Puggies",                   count: null,       rarity: "Secret",       source: "baseline" },
  "los primos":                    { name: "Los Primos",                    count: null,       rarity: "Secret",       source: "baseline" },
  "los tacoritas":                 { name: "Los Tacoritas",                 count: null,       rarity: "Secret",       source: "baseline" },
  "lovin rose":                    { name: "Lovin Rose",                    count: null,       rarity: "Secret",       source: "baseline" },
  "dug dug dug":                   { name: "Dug Dug Dug",                   count: null,       rarity: "Secret",       source: "baseline" },
  "rico dinero":                   { name: "Rico Dinero",                   count: null,       rarity: "Secret",       source: "baseline" },
  "la romantic grande":            { name: "La Romantic Grande",            count: null,       rarity: "Secret",       source: "baseline" },
  "gym bros":                      { name: "Gym Bros",                      count: null,       rarity: "Secret",       source: "baseline" },
  "tirilikalika tirilikalako":     { name: "Tirilikalika Tirilikalako",     count: null,       rarity: "Secret",       source: "baseline" },
  "jolly jolly sahur":             { name: "Jolly Jolly Sahur",             count: null,       rarity: "Secret",       source: "baseline" },
  "fishino clownino":              { name: "Fishino Clownino",              count: null,       rarity: "Secret",       source: "baseline" },
  "antonio":                       { name: "Antonio",                       count: null,       rarity: "Secret",       source: "baseline" },
  "hopilikalika hopilikalako (egg)":{ name: "Hopilikalika Hopilikalako (Egg)",count: null,    rarity: "Secret",       source: "baseline" },
  "la easter grande":              { name: "La Easter Grande",              count: null,       rarity: "Secret",       source: "baseline" },
  "cloverat clapat":               { name: "Cloverat Clapat",               count: null,       rarity: "Secret",       source: "baseline" },
  "quackini snackini":             { name: "Quackini Snackini",             count: null,       rarity: "Secret",       source: "baseline" },
  "quackini snackini (egg)":       { name: "Quackini Snackini (Egg)",       count: null,       rarity: "Secret",       source: "baseline" },
  "los spaghettis":                { name: "Los Spaghettis",                count: null,       rarity: "Secret",       source: "baseline" },
  "los chillis":                   { name: "Los Chillis",                   count: null,       rarity: "Secret",       source: "baseline" },
  "boppin bunny":                  { name: "Boppin Bunny",                  count: null,       rarity: "Secret",       source: "baseline" },
  "elefanto frigo":                { name: "Elefanto Frigo",                count: null,       rarity: "Secret",       source: "baseline" },
  "los hackers":                   { name: "Los Hackers",                   count: null,       rarity: "Secret",       source: "baseline" },
  "fragrama and chocrama":         { name: "Fragrama and Chocrama",         count: null,       rarity: "Secret",       source: "baseline" },
  "la casa boo":                   { name: "La Casa Boo",                   count: null,       rarity: "Secret",       source: "baseline" },
  "signore carapace":              { name: "Signore Carapace",              count: null,       rarity: "Secret",       source: "baseline" },
  "kalika bros":                   { name: "Kalika Bros",                   count: null,       rarity: "Secret",       source: "baseline" },
  "pancake and syrup":             { name: "Pancake and Syrup",             count: null,       rarity: "Secret",       source: "baseline" },
  "ketupat bros":                  { name: "Ketupat Bros",                  count: 6960,       rarity: "Secret",       source: "baseline" },
  "arcadragon":                    { name: "Arcadragon",                    count: 70,         rarity: "Secret",       source: "baseline" },
  "burguro and fryuro":            { name: "Burguro and Fryuro",            count: 148153,     rarity: "Secret",       source: "baseline" },
  "cooki and milki":               { name: "Cooki and Milki",               count: 68538,      rarity: "Secret",       source: "baseline" },
  "cerberus":                      { name: "Cerberus",                      count: 15200,      rarity: "Secret",       source: "baseline" },
  "hydra bunny":                   { name: "Hydra Bunny",                   count: 2318,       rarity: "Secret",       source: "baseline" },
  "la supreme combinasion":        { name: "La Supreme Combinasion",        count: 6858,       rarity: "Secret",       source: "baseline" },
  "love love bear":                { name: "Love Love Bear",                count: 1059,       rarity: "Secret",       source: "baseline" },
  "dragon gingerini":              { name: "Dragon Gingerini",              count: 3429,       rarity: "Secret",       source: "baseline" },
  "griffin":                       { name: "Griffin",                       count: 1985,       rarity: "Secret",       source: "baseline" },
  "ventoliero pavonero":           { name: "Ventoliero Pavonero",           count: 930,        rarity: "Secret",       source: "baseline" },
  "bananito bandito":              { name: "Bananito Bandito",              count: null,       rarity: "Secret",       source: "baseline" },
  "chimnino":                      { name: "Chimnino",                      count: 70,         rarity: "Secret",       source: "baseline" },
  "los noobinis":                  { name: "Los Noobinis",                  count: 700000,     rarity: "Secret",       source: "baseline" },
};

module.exports = { BASELINE_DATA };
